eureka:
  client:
    service-url:
      defaultZone: http://114.67.89.26:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      name: service-zuul
      profile: dev