spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/flysLi/springcloud-config-demo1
          search-paths: respo
          default-label: master
          username: flysLi
          password: a520520
server:
  port: 8888